"""Shared dataclasses and formatting helpers for TubeMind's board workflow.

The board-based UI stores most durable state in SQLite, but the application
still benefits from typed in-memory objects for runtime orchestration and
template rendering. This module keeps those small, cross-cutting structures in
one place so the route, service, and UI layers all operate on the same shapes.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


def now_ms() -> int:
    """Return the current UTC time in milliseconds for durable ordering fields.

    TubeMind stores many user-facing timestamps in SQLite and JSON artifacts.
    Using integer millisecond values keeps ordering inexpensive, avoids locale
    concerns, and matches the existing lightweight persistence style across the
    project.
    """

    return int(time.time() * 1000)


def iso8601_duration_to_seconds(duration: str) -> int:
    """Convert a YouTube ISO-8601 duration like ``PT12M34S`` into seconds.

    YouTube's API returns durations in ISO-8601 format, while the UI and
    filtering logic need plain integer seconds for minimum-length filtering and
    compact display labels.
    """

    if not duration or not isinstance(duration, str) or not duration.startswith("PT"):
        return 0
    match = re.match(r"^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$", duration)
    if not match:
        return 0
    hours = int(match.group(1) or 0)
    minutes = int(match.group(2) or 0)
    seconds = int(match.group(3) or 0)
    return hours * 3600 + minutes * 60 + seconds


def seconds_to_label(seconds: int) -> str:
    """Format whole seconds into a compact human-friendly timestamp label.

    The UI uses these labels for video duration chips and chunk start-time
    references. Keeping this formatting helper shared prevents subtle
    inconsistencies between board cards, detail pages, and retrieval metadata.
    """

    if seconds <= 0:
        return ""
    minutes, sec = divmod(seconds, 60)
    hours, minutes = divmod(minutes, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{sec:02d}"
    return f"{minutes}:{sec:02d}"


def yt_watch_url(video_id: str, offset_seconds: Optional[float] = None) -> str:
    """Build a canonical YouTube watch URL, optionally anchored to a timestamp.

    Note detail pages link users directly back to the supporting source video.
    Returning a normalized watch URL here keeps that behavior consistent whether
    the link came from a stored board video row or a retrieved chunk.
    """

    if offset_seconds is None:
        return f"https://www.youtube.com/watch?v={video_id}"
    return f"https://www.youtube.com/watch?v={video_id}&t={max(0, int(offset_seconds))}s"


@dataclass(slots=True)
class YouTubeVideo:
    """Normalized YouTube video metadata used before and after indexing.

    The raw YouTube API responses are verbose and inconsistent across
    endpoints. This object holds only the fields TubeMind needs for board
    retrieval, note evidence rendering, and source deduplication.
    """

    video_id: str
    title: str
    channel_title: str
    published_at: str
    thumbnail: str
    duration_sec: int
    url: str


@dataclass(slots=True)
class BoardRuntime:
    """Hold the per-board LightRAG runtime and on-disk artifact locations.

    Each board owns its own cumulative knowledge base so follow-up notes stay
    scoped to one topic instead of sharing a single corpus across the user.
    Keeping the runtime metadata together makes it straightforward to lazily
    create, cache, and later shut down board-specific resources.
    """

    board_id: int
    working_dir: Path
    transcript_dir: Path
    rag: object | None = None


@dataclass(slots=True)
class BoardWorkspace:
    """Bundle the data needed to render the main board workspace in one object.

    The workspace route always needs the same coordinated pieces: the list of
    boards for the sidebar, the currently active board, that board's notes, and
    any transient notice or warning generated by the last action. Grouping
    those fields avoids long parameter lists in the UI layer.
    """

    boards: list[dict]
    active_board: dict | None
    notes: list[dict] = field(default_factory=list)
    notice: str = ""
    warning: str = ""
